export const SET_OPEN_MENU = 'SET_OPEN_MENU'
export const SET_OPEN = 'SET_OPEN'

export const POST_REGISTER = 'POST_REGISTER'

export const GET_COUNTRY = 'GET_COUNTRY'
export const GET_PROVINCE = 'GET_PROVINCE'
export const GET_DISTRICT = 'GET_DISTRICT'
export const GET_COMMUNE = 'GET_COMMUNE'
export const GET_TYPE_VIHICLE = 'GET_TYPE_VIHICLE'
export const GET_COLOR = 'GET_COLOR'
export const GET_PLATE_COLOR = 'GET_PLATE_COLOR'
export const GET_BRAND = 'GET_BRAND'
export const GET_NATIONAL_NUMBER = 'GET_NATIONAL_NUMBER'
export const GET_PROVINCE_NUMBER = 'GET_PROVINCE_NUMBER'
export const GET_SERI_VIHICLE = 'GET_SERI_VIHICLE'
export const GET_ADDRESS = 'GET_ADDRESS'

export const GET_COUNTRY_ID = 'GET_COUNTRY_ID'
export const GET_PROVINCE_ID = 'GET_PROVINCE_ID'
export const GET_DISTRICT_ID = 'GET_DISTRICT_ID'
export const GET_COMMUNE_ID = 'GET_COMMUNE_ID'

export const SEARCH_LICENSE_PLATE = 'SEARCH_LICENSE_PLATE'
export const VISIBLE_PROCESS = 'VISIBLE_PROCESS'
export const VISIBLE_UPDATE_STATUS = 'VISIBLE_UPDATE_STATUS'
export const TOGGLE_SUBFORM = 'TOGGLE_SUBFORM'
export const SET_ONE_LINEDATA = 'SET_ONE_LINEDATA'
export const SET_ACTIVEKEY = 'SET_ACTIVEKEY'
export const SET_SEARCH = 'SET_SEARCH'


export const ERROR = 'ERROR'

